[package]
name = "lost-star-badminton"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
actix-cors = "0.5.4"
derive_more = "0.99.17"
dotenv = "0.15.0"
futures = "0.3.18"
serde = { version = "1", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"]}


# mongodb = "2.0.2"
[dependencies.mongodb]
version = "2.1.0"
default-features = false
features = ["async-std-runtime"]
